# Generated by Django 5.1.1 on 2026-01-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_group_alter_comment_created_alter_comment_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
